server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SUPABASE_URL}/auth/v1/jwks

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://user-identity-service
          predicates:
            - Path=/api/auth/**
        
        - id: user-identity-service
          uri: lb://user-identity-service
          predicates:
            - Path=/api/users/**

        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/organizations/**

        - id: emission-reporting-service
          uri: lb://emission-reporting-service
          predicates:
            - Path=/api/emissions/**

        - id: verification-service
          uri: lb://verification-service
          predicates:
            - Path=/api/verifications/**

        - id: credit-issuance-service
          uri: lb://credit-issuance-service
          predicates:
            - Path=/api/credits/**

        - id: trading-service
          uri: lb://trading-service
          predicates:
            - Path=/api/trading/**, /api/transactions/**

        - id: audit-ledger-service
          uri: lb://audit-ledger-service
          predicates:
            - Path=/api/audit/**

        - id: notification-service-ws
          uri: lb://notification-service
          predicates:
            - Path=/ws/**


        - id: geo-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/geo/**
          filters:
            - RewritePath=/api/geo/(?<segment>.*), /$\{segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
